# Just a test config file
detector geometry:
  [
    [0, 15, 0.0, 0.5, -1, 1, 0, 10],
    [1, 4, 0.5, 6.5, -1, 1, 1, 10],
    [1, 4, 7.0, 13, -1, 1, 2, 10],
    [1, 4, 13.5, 19.5, -1, 1, 3, 10],
    [1, 4, 20.0, 24.5, -1, 1, 4, 10],
    [10, 13, 0.5, 3.5, -1, 1, 5, 10],
    [10, 13, 3.5, 6.5, -1, 1, 6, 10],
    [10, 13, 6.5, 9.5, -1, 1, 7, 10],
    [10, 13, 9.5, 12.5, -1, 1, 8, 10],
    [10, 13, 12.5, 15.5, -1, 1, 9, 10],
    [10, 13, 15.5, 18.5, -1, 1, 10, 10],
    [10, 13, 18.5, 21.5, -1, 1, 11, 10],
    [10, 13, 21.5, 24.5, -1, 1, 12, 10],
    [0, 15, 24.5, 25.0, -1, 1, 13, 10],
  ]
detector:
  crystal n subdivision xyz: [2, 2, 2]
  sensitive geometry indices:
    # [13, 14, 15, 16, 17, 18, 19, 20]
    [7]
  inner layer x up-lim: 8
image:
  # dimension xyz: [2, 2, 2]
  dimension xyz: [50, 50, 1]
  voxel per mm xyz: [1.0, 1.0, 1.0]
  # subdivision xyz: [1, 1, 1]
  subdivision xyz: [2, 2, 2]
  detector x-shift: 30
  detector rotation: 0

Debug:
  Point A: [-40, -12.5, 0.5]
  Point B: [11.5, 13.5, 0.5]

out npz filename: mpi-test.npz