# Just a test config file

# Detector space parameters
detector:
  detector geometry:
    [
      [0, 15, 0.0, 0.5, -1, 1, 0, 10],
      [1, 2, 0.5, 10.75, -1, 1, 1, 10],
      [1, 2, 11.25, 24.5, -1, 1, 1, 10],
      [10, 13, 0.5, 3.5, -1, 1, 5, 0.48],
      [10, 13, 3.5, 6.5, -1, 1, 6, 0.48],
      [10, 13, 6.5, 9.5, -1, 1, 7, 0.48],
      [10, 13, 9.5, 12.5, -1, 1, 8, 0.48],
      [10, 13, 12.5, 15.5, -1, 1, 9, 0.48],
      [10, 13, 15.5, 18.5, -1, 1, 10, 0.48],
      [10, 13, 18.5, 21.5, -1, 1, 11, 0.48],
      [10, 13, 21.5, 24.5, -1, 1, 12, 0.48],
      [0, 15, 24.5, 25.0, -1, 1, 13, 10],
    ]

  N-subdivision xyz: [5, 5, 5]

  sensitive geometry indices: [8]

  inner layer x up-lim: 8

# Image space parameters
image:
  
  dimension xyz: [50, 50, 1]
  
  voxel per mm xyz: [1.0, 1.0, 1.0]
  
  N-subdivision xyz: [2, 2, 2]
  


# Image space to detector space relative positioning
detector-to-image:
  # detector front edge to FOV center distance in radial direction
  radial distance: 30 mm
  rotation: 0

Debug:
  Point A: [-40, -12.5, 0.5]
  Point B: [11.5, 13.5, 0.5]

out npz filename: mpi-test.npz
